version: "3"

services:

    shopware:
      image: dockware/dev:latest
      container_name: shopware
      ports:
         - "80:80"
         - "3306:3306"
         - "22:22"
         - "8888:8888"
         - "9999:9999"
         - "9998:9998"
      networks:
         - web
      environment:
         - XDEBUG_ENABLED=1
      volumes:
        - "./src/custom/plugins/MyPlugin:/var/www/html/custom/plugins/MyPlugin"
        # exclude by using anonymous volumes
        - "/var/www/html/custom/plugins/MyPlugin/.git/"
        - "/var/www/html/custom/plugins/MyPlugin/vendor/"
        - "/var/www/html/custom/plugins/MyPlugin/src/Resources/app/administration/node_modules/"
        - "/var/www/html/custom/plugins/MyPlugin/src/Resources/app/storefront/node_modules/"
        - "/var/www/html/custom/plugins/MyPlugin/tests/Cypress/"
        # Thomas Test Plugin
        - "./src/custom/plugins/ThomasTestPlugin:/var/www/html/custom/plugins/ThomasTestPlugin"
        - "/var/www/html/custom/plugins/ThomasTestPlugin/.git/"
        - "/var/www/html/custom/plugins/ThomasTestPlugin/vendor/"
        - "/var/www/html/custom/plugins/ThomasTestPlugin/src/Resources/app/storefront/node_modules/"
        - "/var/www/html/custom/plugins/ThomasTestPlugin/tests/Cypress/"

networks:
  web:
    external: false
